### ISSUE TITLE
challenge period 168h0m0s problems

### ISSUE THREAD

**Issue by 0x6e6f6c61** [base-org/withdrawer#6]
i have waited the challenge period plus a couple hours.  is the bridge back officially open?  is the finalization period longer than 7 days?  the code worked on testnet but seem to have problems for mainnet withdrawal.

**Comment by mehteflon** [comment]
Having the same problem.

**Comment by mdehoog** [comment]
Thank you for reporting, this was due to a bug in the challenge period calculation, fixed with commit 72d9fe94c317010f27257ba31e494c378c3f5eef. Apologies for the delay.

**Comment by mehteflon** [comment]
Thanks for looking into this -- however still getting an error?

"Error completing withdrawal: withdrawal tx 0xefce5b34d7b6262a277774896cff42ce8f4da6a5049aafd8d38ebfac9368eb66 was included in L2 block 2034109 (time 1690857565) but L1 only knows of L2 proposal 2545200 (time 1691879747) at head 604800 (time 17901896) which has not reached output confirmation yet (period is 1691880947)"
